#157 In error page, also show the exception message (#162)
* API: Add attribute "message" to HttpError, include in response. But now, error:

TypeError: Object of type 'ZeroDivisionError' is not JSON serializable

* API: Fix TypeError of previous commit -> needed to manually convert ex_value to string

* App: Add message to HttpError, get it from API call

* App: Show message in error page

* API: For errors received from Spotify API, put message into message attribute (instead of title), set title to "Spotify API Error"

* API: In SpotifyClient, extract method __create_http_error_from_response_data

* App: In error page, show status code separately, as the message

* API: Fix: Swapped title & message for Spotify API errors