#214 Consider key & mode as one coherent attribute (#305)
* [App] Add missing exception handling for track_view.py

* [API] Add constants for key & mode pairs in Track

* [API] Fix name of constants

* (Not working) [App] Add logic in App to get key_and_mode_pair from API and render it.

But getting error in App, track.py:
if index < 0 or index >= len(_list):
TypeError: '<' not supported between instances of 'list' and 'int'

* [API] Fix: Remove trailing commas for KeyAndModePairs constants. this way, the values were a tuple instead of single int, this was reason for TypeError in App

* [App] Add display name for key_and_mode_pair

* [App] Adjust in track.html so key & mode pair is shown below mode

* [App] Fix order of header columns in tracks_table.html

* [API] Add mappings for all values in Track.__get_key_and_mode_pair. -> No need to map each one explicitly as started first, can just calculate

* [API] Add sort option for key_and_mode_pair

* [API] Remove separate sort options for key & mode. Provide no benefit because the new sort option does both, first sorts by mode, then by key.

* [App] Remove separate columns "Key" & "Mode" from tracks tables. Provide no benefit anymore because info combined in the new column

* [App] Remove obsolete code