#237 Add smoke tests: In App, one for each route (#239)
* Add deployment scripts for new test environment

* Add smoke test for index route

* Add test_playlist. Unexpectedly passes even though API is not running

* [App] Adjust render_template call for error template so returns proper status code, now test_playlist fails as expected because API is not running

* [API] Add deployment scripts for test environment. Could alternatively just re-use dev for API, but is cleaner this way

* Adjust ports, starting from 5000 so can easier remember them

* [App] Add additional deployment files for test environment so can additionally test it in browser

* Remove TODO in test_playlist, now fails as expected if API is not running and passes if API is running

* [API] For test env, rename run.sh to run_app.sh as done for App test env. This way is consistent, makes sense to distinguish when adding unit tests for API in future

* Add test_choose_one_playlist

* Add test_choose_playlists_for_comparison

* In test_smoke.py, extract helper method __test_get_request

* Add tests for remaining routes that do not need API

* Remove accidentally copied test

* In test_smoke.py, move reading of config file into setUp and move usage of base url into __test_get_request to reduce duplication

* Remove TODO

* Add test_compare_playlists

* [App] In compare_playlists_view.py, return proper status code for error so test_compare_playlist fails as expected with invalid playlist id

* Fix test_compare_playlists, now passes as expected

* Clean up test code: encode query params rather than hardcoding url

* Add test_track

* In test_view, return proper status code for error, now test_track fails as expected. Reproduces issue #238

* Add test_search_tracks

* Add some TODOs for next tests

* In test_smoke.py, define variables rather than inlining to be more explicit, test serves as documentation

* In search_tracks_view.py, return proper status code for error. Now test_search_tracks fails as expected due to #238

* Add TODO

* Add test_playlist_sort_tracks (passes), for one value of sort_by only

* Trying parametrized test for test_playlist_sort_tracks so it tests all attributes, but does not work

Error: TypeError: test_playlist_sort_tracks() missing 1 required positional argument: 'sort_by'

* Fix test_playlist_sort_tracks (passes). Use bad practice of for loop instead of parametrized because did not work, raised TypeError: test_playlist_sort_tracks() missing 1 required positional argument: 'sort_by'

* Small refactoring in test code

* Add missing attributes for test_playlist_sort_tracks

* Fix test_compare_playlists, could not get playlist 2

* Adjust test_playlist_sort_tracks to only test one attribute

-> Else would take too long and also too many requests to Spotify API. For Smoke test this is sufficient, only broad test that basic functionality works.

* Remove useless comments

* Add test_attribute_distribution

* In attribute-distribution endpoint, return proper status code. Now test_attribute_distribution fails as expected if API is not running

* In test code, extract constants PLAYLIST_ID_1 & PLAYLIST_ID_2 to avoid duplication. All tests should use the same playlists anyway.

* Add test_attribute_distribution_for_key & test_attribute_distribution_for_mode to reproduce #236. Works, they fail

* Add test_compare_attribute_distribution

* Return proper status code in endpoint compare_attribute_distribution_of_playlists, now test_compare_attribute_distribution fails as expected if API is not running

* Add test_compare_attribute_distribution_for_key & test_compare_attribute_distribution_for_mode to reproduce #236

* Return correct status code in remaining endpoints

* Extract constant TRACK_ID (even though only used once, just for consistency)