#115 Move remaining logic into API (#118)
* Adjust code in App, now fails as expected because API does not yet return the new data:

KeyError: 'total_duration_ms'

* API: Calculate values & add them to response data

* App: Adjust code for key & mode, now shows just numbers as expected

* API: Return key & mode as string

* API: Remove TODO & add comment why it makes sense for camelot to be determined in SpotifyClient, even though it does not directly depend on SpotifyAPI

* App: Inline getters