Fix test_playlist_sort_tracks (passes). Use bad practice of for loop instead of parametrized because did not work, raised TypeError: test_playlist_sort_tracks() missing 1 required positional argument: 'sort_by'