Trying parametrized test for test_playlist_sort_tracks so it tests all attributes, but does not work
Error: TypeError: test_playlist_sort_tracks() missing 1 required positional argument: 'sort_by'